trigger:
  - master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn --frozen-lockfile
  displayName: 'Install Dependencies'

- script: yarn lint
  displayName: 'Lint Source'

- script: |
    yarn cover -- --ci --reporters=default --reporters=jest-junit --coverageReporters=lcov --coverageReporters=cobertura
    ./node_modules/.bin/codecov
  displayName: 'Run Tests and Coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
  displayName: 'Publish Test Results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'
  displayName: 'Publish Code Coverage Results'

- script: yarn build
  displayName: 'Run Build'

- script: |
    for d in packages/*/; do
      if [ -d "$d" ]; then
        package=$(basename $d)

        if [ -d "$d/dist/" ]; then
          echo "Copying dist for $package"

          cp -R $d/dist/ $(Build.ArtifactStagingDirectory)/$package
        fi
      fi
    done
  displayName: 'Copy Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'package'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
