[build]
publish = "dist"

command = "yarn build:storybook && mkdir -p dist/angular && cp -R packages/storybook-ui/dist dist && cp -R packages/storybook-angular/dist dist/angular"

[[redirects]]
from = "/angular*"
to = "/angular/index.html"
status = 200