[build]
publish = "dist/public"

command = "yarn build:storybook && mkdir -p dist/public/angular cp -R packages/storybook-ui/dist/public dist/public && cp -R packages/storybook-angular/dist/public dist/public/angular"

[[redirects]]
from = "/angular/*"
to = "/public/angular/index.html"

[[redirects]]
from = "/*"
to = "/public/index.html"