version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-cache-v1-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-cache-v1-

      - run: 
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint Source
          command: yarn lint

      - run: 
          name: Run Tests
          command: yarn test

      - run: 
          name: Build
          command: yarn build

      - run: 
          name: Copy Artifacts
          command: ./scripts/copy-artifacts.sh

      - store_artifacts:
          path: dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
