name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install deps
      run: yarn --frozen-lockfile
      
    - name: Lint
      run: yarn lint
      
    - name: Run tests and coverage
      run: yarn cover -- -- --ci

    - name: Publish coverage
      run: yarn codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
    - name: Copy artifacts
      run: |
        for d in packages/*/; do
          if [ -d "$d" ]; then
            package=$(basename $d)

            if [ -d "$d/dist/" ]; then
              echo "Copying dist for $package"

              cp -R $d/dist/ .out/$package
            fi
          fi
        done
    
    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: .out/ 
    
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: packages

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        for d in packages/*/; do
          if [ -d "$d" ]; then
            package=$(basename $d)

            echo "Copying dist for $package"

            npm publish $d --access public --tag next
          fi
        done
        
  
