name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install deps
      run: yarn --frozen-lockfile
      
    - name: Lint
      run: yarn lint
      
    - name: Run tests and coverage
      run: yarn cover -- -- --ci

    - name: Publish coverage
      run: yarn codecov
      
    - name: Copy artifacts
      run: |
        for d in packages/*/; do
          if [ -d "$d" ]; then
          package=$(basename $d)

          if [ -d "$d/dist/" ]; then
            echo "Copying dist for $package"

            cp -R $d/dist/ .out/$package
          fi
        fi
        done
    
    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: .out/ 
      
